# Run by source group_ports.tcl
create_hw_probe -m probe0[22]       mgt_rxready_s                        [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[21]       mgt_txready_s                        [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[20:13]    gbtbank_rxbitslip_rst_cnt_s[7:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[12:11]    gbtBank_txEncodingSel[1:0]           [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[10:9]     gbtBank_rxEncodingSel[1:0]           [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[8]        RX_ENCODING_SEL_i                    [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[7]        gbt_rxreset_s                        [get_hw_ilas hw_ila_1]            
create_hw_probe -m probe0[6]        mgt_rxreset_s                        [get_hw_ilas hw_ila_1]            
create_hw_probe -m probe0[5]        TX_ENCODING_SEL_i                    [get_hw_ilas hw_ila_1]            
create_hw_probe -m probe0[4]        gbt_txreset_s                        [get_hw_ilas hw_ila_1]            
create_hw_probe -m probe0[3]        mgt_txreset_s                        [get_hw_ilas hw_ila_1]            
create_hw_probe -m probe0[2]        GBTBANK_MANUAL_RESET_RX_I            [get_hw_ilas hw_ila_1]            
create_hw_probe -m probe0[1]        GBTBANK_MANUAL_RESET_TX_I            [get_hw_ilas hw_ila_1]
create_hw_probe -m probe0[0]        GBTBANK_GENERAL_RESET_I              [get_hw_ilas hw_ila_1]

create_hw_probe -m probe0[205]      gbt_rxclkenLogic_s                   [get_hw_ilas hw_ila_2]
create_hw_probe -m probe0[204]      gbtbank_gbtrxready_lost_flag_s       [get_hw_ilas hw_ila_2]            
create_hw_probe -m probe0[203:120]  gbtbank_rx_bitmodified_flag_s[83:0]  [get_hw_ilas hw_ila_2]            
create_hw_probe -m probe0[119]      gbtbank_rx_errordetected_s           [get_hw_ilas hw_ila_2]            
create_hw_probe -m probe0[118]      gbt_rxready_s                        [get_hw_ilas hw_ila_2]            
create_hw_probe -m probe0[117]      mgt_headerflag_s                     [get_hw_ilas hw_ila_2]            
create_hw_probe -m probe0[116]      gbtbank_rx_isdata_sel_s              [get_hw_ilas hw_ila_2]            
create_hw_probe -m probe0[115:84]   wb_rxdata_s[31:0]                    [get_hw_ilas hw_ila_2]
create_hw_probe -m probe0[83:0]     gbt_rxdata_s[83:0]                   [get_hw_ilas hw_ila_2]

create_hw_probe -m probe0[117]      gbt_txclken_s                        [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[116]      GBTBANK_TX_ISDATA_SEL_I              [get_hw_ilas hw_ila_3]            
create_hw_probe -m probe0[115:84]   wb_txdata_s[31:0]                    [get_hw_ilas hw_ila_3]
create_hw_probe -m probe0[83:0]     gbt_txdata_s[83:0]                   [get_hw_ilas hw_ila_3]
